language: java
jdk:
  - openjdk11

sudo: required

services:
  - docker
  - mysql
  - redis-server

env:
  global:
    - MYSQL_USER="root"
    - MYSQL_HOST="127.0.0.1"
    - MYSQL_DB="qicoo2db"
    - MYSQL_PORT="3306"
    - REDIS_HOST="localhost"
    - REDIS_PORT="6379"
    - DOCKER_CACHE_DIR="docker-cache"
    - DOCKER_CACHE_TAR="saved_images.tar"
    - DOCKER_IMAGE_NAME="cndjp/qicoo-api-kt"

before_install:
  - export TZ=Asia/Tokyo
  - curl -s api.sdkman.io | bash
  - source /home/travis/.sdkman/bin/sdkman-init.sh # ターミナル上での表示結果
  - sdk list gradle
  - sdk install gradle 5.6.2
  - sdk default gradle 5.6.2

before_script:
  - echo 'Asia/Tokyo' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - date
  - mkdir /opt/bin
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git casey/just --target x86_64-unknown-linux-musl --to /opt/bin/
  - export PATH=/opt/bin:$PATH
  - just version
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DB}" | mysql -h${MYSQL_HOST} -uroot
  - echo 'set global time_zone = "Asia/Tokyo"' | mysql -h${MYSQL_HOST} -uroot
  - |
    if [[ -f "${HOME}/${DOCKER_CACHE_DIR}/${DOCKER_CACHE_TAR}" ]]; then docker load < "${HOME}/${DOCKER_CACHE_DIR}/${DOCKER_CACHE_TAR}"; fi

script:
  - just test
  - just build
  - just docker-build

after_success:
  - |
    mkdir -p ${DOCKER_CACHE_DIR}
    docker save -o "${HOME}/${DOCKER_CACHE_DIR}/${DOCKER_CACHE_TAR}" "${DOCKER_IMAGE_NAME}:$(git rev-parse HEAD)"
    ls "${HOME}/${DOCKER_CACHE_DIR}/${DOCKER_CACHE_TAR}"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - ${HOME}/${DOCKER_CACHE_DIR}
    - ${HOME}/.gradle/caches/
    - ${HOME}/.gradle/wrapper/
    - ${HOME}/.android/build-cache