language: java
jdk:
- openjdk11
sudo: required
services:
- docker
- mysql
- redis-server
env:
  global:
  - MYSQL_USER="root"
  - MYSQL_HOST="127.0.0.1"
  - MYSQL_DB="qicoo2db"
  - MYSQL_PORT="3306"
  - REDIS_HOST="localhost"
  - REDIS_PORT="6379"
  - DOCKER_REPO='cndjp/qicoo-api-kt'
  - secure: cyQe7BjQRDI6Z74AJ9AYpLu8kOuDQM0C4PqBM7jkHiNdsmfRMWeqoQyokf1R7AmuQkxhfrLcfXQOgLw23GZF51QI9EPxAn5pBgu2CWtsKchG5f4WD/pqfJ7P9BsUUjnkREY83Li+veOeb0JvcBQWoQla9I1rxa/MyYhG2BXKrkd7Jud4o4sLIie+mi9hHxyrEYjhQnnuO6upjoZ3XFqSNb2x8HZlQl8sUMzuWyrFqSemTW0ThcqOgiZp54R8vRyNt8hDKExI6AnbVG6RffZfC1h59x9/OTgpFfntgwhA7PIEyGGyJa8AikDIgg3gAhDtkp2KYCEfFacRs9+6fFdZp5J9rbs/aY44AA8lWgXO4mhEgYCC/JQfRQVxRGZQGnR9MFqI1+/69fnwN2VFo29qsDwQt1bYZ8uaDpWWc4i5yhDvLs27kzpg2YFhNuRqFsPtFqgPqoniRCxbCuiRqXYC04tcUwXZJwhwRVr4ONwTLjsuBW9GKvPfVTCKCs+tpg4pQDYSVc8bK/OUuEpRHM4cdgzv7WPEUyZEZvN/cnuE0MasYiro3I/FOPVUC88E6EYN1Nq6FIfcEUF5EJOU6YvyuM/521m8R+lL1dSZhslSisvj+dlj2fjqRexg7E47KpgYPlaxkdJMIi1+/C7/BMggzC10WA2r6lwAhwAfRDuNza0=
before_install:
- export TZ=Asia/Tokyo
- curl -s api.sdkman.io | bash
- source /home/travis/.sdkman/bin/sdkman-init.sh
- sdk list gradle
- sdk install gradle 5.6.2
- sdk default gradle 5.6.2
before_script:
- echo 'Asia/Tokyo' | sudo tee /etc/timezone
- sudo dpkg-reconfigure --frontend noninteractive tzdata
- date
- mkdir /opt/bin
- curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git casey/just
  --target x86_64-unknown-linux-musl --to /opt/bin/
- export PATH=/opt/bin:$PATH
- just version
- mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
- echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DB}" | mysql -h${MYSQL_HOST} -uroot
- echo 'set global time_zone = "Asia/Tokyo"' | mysql -h${MYSQL_HOST} -uroot
script:
- just test
- just build
- just docker-release
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  bundler: true
  directories:
  - "${HOME}/.gradle/caches/"
  - "${HOME}/.gradle/wrapper/"
  - "${HOME}/.android/build-cache"
